# Perform feature transformation:

**Transformation of feature**

why transformation of feature are required?

1.Linear Regression -- Gradient Descent--Global Minima

2.Algorithms like KNN, K-Means , Hierarichal clustering--eucledian distance

Every point has some vectors and directions

Deep Learning Techniques( standardization,scaling)

1.ANN-->Global Minima Gradient

2.CNN

3.RNN

**Standardization(why?)**

standardization comes into picture when features of input data set have large difference between their ranges, 
or simply when they are measured in different measurement units(eg. pounds , meters , miles...etc)

I try to bring all thevariable or features to a similar scale. standardization means centering the variable at zero.

z=(x- x_mean)/std



In [3]:
import numpy as np
import pandas as pd

dataset=pd.read_csv('adult.csv')
dataset=dataset.head(10)
dataset

age         workclass  fnlwgt     education  educational-num  \
0   25           Private  226802          11th                7   
1   38           Private   89814       HS-grad                9   
2   28         Local-gov  336951    Assoc-acdm               12   
3   44           Private  160323  Some-college               10   
4   18                 ?  103497  Some-college               10   
5   34           Private  198693          10th                6   
6   29                 ?  227026       HS-grad                9   
7   63  Self-emp-not-inc  104626   Prof-school               15   
8   24           Private  369667  Some-college               10   
9   55           Private  104996       7th-8th                4   

       marital-status         occupation   relationship   race  gender  \
0       Never-married  Machine-op-inspct      Own-child  Black    Male   
1  Married-civ-spouse    Farming-fishing        Husband  White    Male   
2  Married-civ-spouse    Protective-serv        Husband  White    Male   
3  Married-civ-spouse  Machine-op-inspct        Husband  Black    Male   
4       Never-married                  ?      Own-child  White  Female   
5       Never-married      Other-service  Not-in-family  White    Male   
6       Never-married                  ?      Unmarried  Black    Male   
7  Married-civ-spouse     Prof-specialty        Husband  White    Male   
8       Never-married      Other-service      Unmarried  White  Female   
9  Married-civ-spouse       Craft-repair        Husband  White    Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States  <=50K  
1             0             0              50  United-States  <=50K  
2             0             0              40  United-States   >50K  
3          7688             0              40  United-States   >50K  
4             0             0              30  United-States  <=50K  
5             0             0              30  United-States  <=50K  
6             0             0              40  United-States  <=50K  
7          3103             0              32  United-States   >50K  
8             0             0              40  United-States  <=50K  
9             0             0              10  United-States  <=50K

In [9]:
import pandas as pd
dataset=pd.read_csv('adult.csv')
coln_used=(['age','educational-num','hours-per-week','income'])
dataset.head(10)

age         workclass  fnlwgt     education  educational-num  \
0   25           Private  226802          11th                7   
1   38           Private   89814       HS-grad                9   
2   28         Local-gov  336951    Assoc-acdm               12   
3   44           Private  160323  Some-college               10   
4   18                 ?  103497  Some-college               10   
5   34           Private  198693          10th                6   
6   29                 ?  227026       HS-grad                9   
7   63  Self-emp-not-inc  104626   Prof-school               15   
8   24           Private  369667  Some-college               10   
9   55           Private  104996       7th-8th                4   

       marital-status         occupation   relationship   race  gender  \
0       Never-married  Machine-op-inspct      Own-child  Black    Male   
1  Married-civ-spouse    Farming-fishing        Husband  White    Male   
2  Married-civ-spouse    Protective-serv        Husband  White    Male   
3  Married-civ-spouse  Machine-op-inspct        Husband  Black    Male   
4       Never-married                  ?      Own-child  White  Female   
5       Never-married      Other-service  Not-in-family  White    Male   
6       Never-married                  ?      Unmarried  Black    Male   
7  Married-civ-spouse     Prof-specialty        Husband  White    Male   
8       Never-married      Other-service      Unmarried  White  Female   
9  Married-civ-spouse       Craft-repair        Husband  White    Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States  <=50K  
1             0             0              50  United-States  <=50K  
2             0             0              40  United-States   >50K  
3          7688             0              40  United-States   >50K  
4             0             0              30  United-States  <=50K  
5             0             0              30  United-States  <=50K  
6             0             0              40  United-States  <=50K  
7          3103             0              32  United-States   >50K  
8             0             0              40  United-States  <=50K  
9             0             0              10  United-States  <=50K

In [10]:
dataset['age'].fillna(dataset.age.median(),inplace=True)

In [11]:
dataset.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

**independent and dependent feature**

In [12]:
x=dataset.iloc[:,1:]
y=dataset.iloc[:,0]

In [13]:
x

workclass  fnlwgt     education  educational-num  \
0           Private  226802          11th                7   
1           Private   89814       HS-grad                9   
2         Local-gov  336951    Assoc-acdm               12   
3           Private  160323  Some-college               10   
4                 ?  103497  Some-college               10   
...             ...     ...           ...              ...   
48837       Private  257302    Assoc-acdm               12   
48838       Private  154374       HS-grad                9   
48839       Private  151910       HS-grad                9   
48840       Private  201490       HS-grad                9   
48841  Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States  <=50K  
1                 0             0              50  United-States  <=50K  
2                 0             0              40  United-States   >50K  
3              7688             0              40  United-States   >50K  
4                 0             0              30  United-States  <=50K  
...             ...           ...             ...            ...    ...  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K  

[48842 rows x 14 columns]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33, random_state=42)

In [15]:
x_train

workclass  fnlwgt     education  educational-num  \
5551     Private  154117       HS-grad                9   
36721    Private  440607     Preschool                1   
2638   Local-gov  197822     Bachelors               13   
36214    Private  211601  Some-college               10   
27010  Local-gov  121998  Some-college               10   
...          ...     ...           ...              ...   
11284    Private  635913       HS-grad                9   
44732    Private  107624  Some-college               10   
38158    Private  250135  Some-college               10   
860    State-gov   96652     Assoc-voc               11   
15795    Private  176118       Masters               14   

              marital-status       occupation    relationship   race  gender  \
5551               Separated     Craft-repair  Other-relative  White  Female   
36721     Married-civ-spouse   Prof-specialty         Husband  Other    Male   
2638           Never-married   Prof-specialty       Own-child  White  Female   
36214          Never-married     Adm-clerical       Own-child  Black  Female   
27010     Married-civ-spouse  Exec-managerial         Husband  White    Male   
...                      ...              ...             ...    ...     ...   
11284  Married-spouse-absent    Other-service   Not-in-family  Black    Male   
44732     Married-civ-spouse     Craft-repair         Husband  White    Male   
38158               Divorced  Exec-managerial   Not-in-family  White  Female   
860                Separated     Adm-clerical       Unmarried  Black  Female   
15795     Married-civ-spouse   Prof-specialty         Husband  White    Male   

       capital-gain  capital-loss  hours-per-week native-country income  
5551              0             0              40  United-States  <=50K  
36721             0             0              30         Mexico  <=50K  
2638              0             0              40  United-States  <=50K  
36214             0             0              40  United-States  <=50K  
27010         15024             0              40  United-States   >50K  
...             ...           ...             ...            ...    ...  
11284             0             0              40  United-States  <=50K  
44732             0             0              50  United-States  <=50K  
38158             0             0              40  United-States  <=50K  
860               0             0              40  United-States  <=50K  
15795             0             0               7  United-States   >50K  

[32724 rows x 14 columns]

**standarisation : we use the standardscaler from sklearn library**

In [19]:
from sklearn.preprocessing import StandardScaler

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


df = pd.DataFrame({
    'Income': [40000, 50000, 60000, 65000,45000],
    'Age': [25, 38, 28, 44, 18],
    'Occupation': ['Machine-op-inspct','Farming-fishing','Protective-serv','Machine-op-inspct','?']
})


In [33]:
df_scaled = df.copy()
col_names = ['Income', 'Age']
features = df_scaled[col_names]


In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df_scaled[col_names] = scaler.fit_transform(features.values)
df_scaled

Income       Age         Occupation
0 -1.293993 -0.603023  Machine-op-inspct
1 -0.215666  0.796851    Farming-fishing
2  0.862662 -0.279975    Protective-serv
3  1.401826  1.442947  Machine-op-inspct
4 -0.754829 -1.356801                  ?

In [35]:
df_scaled.describe()

Income           Age
count  5.000000e+00  5.000000e+00
mean   2.220446e-17 -1.332268e-16
std    1.118034e+00  1.118034e+00
min   -1.293993e+00 -1.356801e+00
25%   -7.548294e-01 -6.030227e-01
50%   -2.156655e-01 -2.799748e-01
75%    8.626622e-01  7.968514e-01
max    1.401826e+00  1.442947e+00

**step9**

In [43]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [44]:
iris=datasets.load_iris()

In [45]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [48]:
target='income'
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [50]:
x=iris.data
y=iris.target

In [51]:
x.shape

(150, 4)

In [52]:
y.shape

(150,)

In [55]:
clf=RandomForestClassifier()
clf.fit(x,y)

RandomForestClassifier()

In [56]:
print(clf.feature_importances_)

[0.10269424 0.02612034 0.42979497 0.44139045]


In [57]:
x[0]

array([5.1, 3.5, 1.4, 0.2])

In [58]:
print(clf.predict([[5.1, 3.5, 1.4, 0.2]]))

[0]


In [59]:
print(clf.predict(x[[0]]))

[0]


In [62]:
clf.fit(iris.data,iris.target_names[iris.target])

RandomForestClassifier()

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [64]:
x_train.shape,y_train.shape

((120, 4), (120,))

In [65]:
x_test.shape,y_test.shape

((30, 4), (30,))

In [66]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [67]:
print(clf.predict([[5.1, 3.5, 1.4, 0.2]]))

[0]


In [68]:
print(clf.predict_proba([[5.1,3.5,1.4,0.2]]))

[[1. 0. 0.]]


In [69]:
print(clf.predict(x_test))

[1 0 0 0 0 0 1 0 1 1 2 1 2 2 0 2 2 1 2 2 0 2 1 0 2 0 1 0 1 2]
