In [1]:
# Arrays

import numpy

def arrays(arr):
    return numpy.array(arr[::-1],float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

# Sample Input
# 1 2 3 4 -8 -10

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
# shape and reshape

import numpy as np
N=np.array(list(map(int,input().split())))

N.shape=(3,3)
print(N)

# Sample Input
# 1 2 3 4 5 6 7 8 9

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# concatenate

import numpy as np
N, M, P = map(int,input().split())
N_arr = np.array([input().split() for _ in range(N)],int)
M_arr = np.array([input().split() for _ in range(M)],int)
print(np.concatenate((N_arr, M_arr), axis = 0))


# Sample Input
# 4 3 2
# 1 2
# 1 2 
# 1 2
# 1 2
# 3 4
# 3 4
# 3 4 

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [8]:
# zeros and ones

import numpy as np
N = tuple(map(int,input().strip().split()))
zero = np.zeros(N, dtype=np.int)
print (zero)
one = np.ones(N, dtype=np.int)
print (one)

# sample ip
# 3 3 3 

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [9]:
# transpose and flatten

import numpy as np
n,m=map(int,input().split())
arr=np.array([input().strip().split() for _ in range(n)])
print(arr.transpose())
print(arr.flatten())

# Sample Input
# 2 2
# 1 2
# 3 4

2 2
1 2
3 4
[['1' '3']
 ['2' '4']]
['1' '2' '3' '4']


In [10]:
# eye and identity

import numpy as np
np.set_printoptions(sign=' ')
n,m=map(int, input().split())
# m=map(int, input().split())
res=np.eye(n,m)
print(res)

# sample ip
# 3 3

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [14]:
# import numpy as np
N,M=map(int,input().split())
# M=np.array(input().split())

A = np.array([input().split() for _ in range(N)], int)
B = np.array([input().split() for _ in range(N)], int)

print(A+B)
print(A-B)
print(A*B)
print(np.array(A/B,int))
print(A%B)
print(A**B)


# sample ip
# 1 4
# 1 2 3 4
# 5 6 7 8

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [15]:
# floor,ceil,rint

import numpy as np
np.set_printoptions(sign=' ')
A = np.array(input().split(), float)
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))


# Sample Input
# 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [16]:
# sum and prod

import numpy as np
N,M=map(int,input().split())
arr=np.array([input().split() for _ in range(N)] , dtype=int)
print(np.prod(np.sum(arr,axis=0)))

# Sample Input
# 2 2
# 1 2
# 3 4

2 2
1 2
3 4
24


In [22]:
# mean , var , std

import numpy as np
n,m=map(int,input().split())

arr=np.array([input().split() for _ in range(n)] , float)

print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(round(np.std(arr,axis=None),11))

# Sample Input
# 2 2
# 1 2
# 3 4

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [23]:
#dot and cross 

import numpy as np
n= int(input())
a = np.array([input().split() for _ in range(n)],int)
b = np.array([input().split() for _ in range(n)],int)
res=np.dot(a,b)
print(res)

# Sample Input
# 2
# 1 2
# 3 4
# 1 2
# 3 4


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [24]:
# inner and outer

import numpy as np
A=np.array(input().split(),int)
B=np.array(input().split(),int)
print(np.inner(A,B),sep='\n')
print(np.outer(A,B),sep='\n')


# Sample Input
# 0 1
# 2 3

0 1
2 3
3
[[0 0]
 [2 3]]


In [25]:
# polynomials

import numpy as np
p = list(map(float, input().split()))
x=np.polyval(p, float(input()))
print(x)

# Sample Input
# 1.1 2 3
# 0

1.1 2 3
0 
3.0


In [26]:
# linear algebra

import numpy as np
np.set_printoptions(legacy='1.13')
N=int(input())
A=np.array([input().split() for _ in range(N)],float)
print(np.linalg.det(A))

# Sample Input
# 2
# 1.1 1.1
# 1.1 1.1

2
1.1 1.1
1.1 1.1
0.0
